import 'package:promedia_v2/food_item.dart';


class TKPIData {
  static final List<FoodItem> foods = [
    // ========== SEREALIA DAN HASIL OLAHANNYA ==========
    FoodItem(
      name: 'Nasi Putih',
      category: 'Serealia',
      energyKcal: 180,
      protein: 4.0,
      fat: 0.4,
      carbohydrate: 40.0,
      fiber: 0.3,
    ),
    FoodItem(
      name: 'Nasi Merah',
      category: 'Serealia',
      energyKcal: 149,
      protein: 3.2,
      fat: 1.0,
      carbohydrate: 32.5,
      fiber: 2.0,
    ),
    FoodItem(
      name: 'Nasi Kuning',
      category: 'Serealia',
      energyKcal: 240,
      protein: 4.5,
      fat: 8.0,
      carbohydrate: 38.0,
      fiber: 0.4,
    ),
    FoodItem(
      name: 'Nasi Goreng',
      category: 'Serealia',
      energyKcal: 267,
      protein: 5.8,
      fat: 11.2,
      carbohydrate: 35.6,
      fiber: 0.8,
    ),
    FoodItem(
      name: 'Nasi Uduk',
      category: 'Serealia',
      energyKcal: 196,
      protein: 3.0,
      fat: 3.2,
      carbohydrate: 38.9,
      fiber: 0.5,
    ),
    FoodItem(
      name: 'Lontong',
      category: 'Serealia',
      energyKcal: 117,
      protein: 2.0,
      fat: 0.2,
      carbohydrate: 27.0,
      fiber: 0.2,
    ),
    FoodItem(
      name: 'Ketupat',
      category: 'Serealia',
      energyKcal: 117,
      protein: 2.0,
      fat: 0.2,
      carbohydrate: 27.0,
      fiber: 0.2,
    ),
    FoodItem(
      name: 'Bubur Nasi',
      category: 'Serealia',
      energyKcal: 44,
      protein: 1.0,
      fat: 0.1,
      carbohydrate: 9.8,
      fiber: 0.1,
    ),
    FoodItem(
      name: 'Roti Tawar Putih',
      category: 'Serealia',
      energyKcal: 248,
      protein: 8.0,
      fat: 1.2,
      carbohydrate: 50.0,
      fiber: 0.5,
    ),
    FoodItem(
      name: 'Roti Gandum',
      category: 'Serealia',
      energyKcal: 246,
      protein: 9.0,
      fat: 3.5,
      carbohydrate: 45.2,
      fiber: 7.0,
    ),
    FoodItem(
      name: 'Mie Kuning',
      category: 'Serealia',
      energyKcal: 286,
      protein: 8.0,
      fat: 3.3,
      carbohydrate: 55.0,
      fiber: 1.0,
    ),
    FoodItem(
      name: 'Mie Bihun',
      category: 'Serealia',
      energyKcal: 364,
      protein: 0.8,
      fat: 0.5,
      carbohydrate: 87.0,
      fiber: 0.5,
    ),
    FoodItem(
      name: 'Makaroni',
      category: 'Serealia',
      energyKcal: 371,
      protein: 13.0,
      fat: 1.5,
      carbohydrate: 75.0,
      fiber: 3.0,
    ),
    
    // ========== UMBI-UMBIAN ==========
    FoodItem(
      name: 'Kentang Rebus',
      category: 'Umbi',
      energyKcal: 62,
      protein: 2.1,
      fat: 0.2,
      carbohydrate: 13.5,
      fiber: 0.5,
    ),
    FoodItem(
      name: 'Kentang Goreng',
      category: 'Umbi',
      energyKcal: 312,
      protein: 3.8,
      fat: 15.5,
      carbohydrate: 40.3,
      fiber: 3.3,
    ),
    FoodItem(
      name: 'Ubi Jalar Kuning',
      category: 'Umbi',
      energyKcal: 123,
      protein: 1.8,
      fat: 0.4,
      carbohydrate: 27.9,
      fiber: 3.0,
    ),
    FoodItem(
      name: 'Singkong Rebus',
      category: 'Umbi',
      energyKcal: 146,
      protein: 1.2,
      fat: 0.3,
      carbohydrate: 34.7,
      fiber: 0.9,
    ),
    FoodItem(
      name: 'Talas',
      category: 'Umbi',
      energyKcal: 98,
      protein: 1.9,
      fat: 0.2,
      carbohydrate: 23.7,
      fiber: 0.5,
    ),
    
    // ========== PROTEIN HEWANI ==========
    FoodItem(
      name: 'Ayam Kampung Rebus',
      category: 'Protein Hewani',
      energyKcal: 204,
      protein: 25.9,
      fat: 10.2,
      carbohydrate: 0.0,
      fiber: 0.0,
    ),
    FoodItem(
      name: 'Ayam Goreng',
      category: 'Protein Hewani',
      energyKcal: 298,
      protein: 27.3,
      fat: 19.5,
      carbohydrate: 3.8,
      fiber: 0.0,
    ),
    FoodItem(
      name: 'Ayam Bakar',
      category: 'Protein Hewani',
      energyKcal: 229,
      protein: 27.3,
      fat: 12.6,
      carbohydrate: 0.0,
      fiber: 0.0,
    ),
    FoodItem(
      name: 'Daging Sapi',
      category: 'Protein Hewani',
      energyKcal: 207,
      protein: 18.8,
      fat: 14.0,
      carbohydrate: 0.0,
      fiber: 0.0,
    ),
    FoodItem(
      name: 'Daging Kambing',
      category: 'Protein Hewani',
      energyKcal: 154,
      protein: 16.6,
      fat: 9.2,
      carbohydrate: 0.0,
      fiber: 0.0,
    ),
    FoodItem(
      name: 'Hati Ayam',
      category: 'Protein Hewani',
      energyKcal: 134,
      protein: 19.0,
      fat: 5.9,
      carbohydrate: 1.0,
      fiber: 0.0,
    ),
    FoodItem(
      name: 'Telur Ayam Rebus',
      category: 'Protein Hewani',
      energyKcal: 154,
      protein: 12.4,
      fat: 10.8,
      carbohydrate: 0.7,
      fiber: 0.0,
    ),
    FoodItem(
      name: 'Telur Dadar',
      category: 'Protein Hewani',
      energyKcal: 199,
      protein: 10.3,
      fat: 17.0,
      carbohydrate: 0.6,
      fiber: 0.0,
    ),
    FoodItem(
      name: 'Ikan Bandeng',
      category: 'Protein Hewani',
      energyKcal: 129,
      protein: 20.0,
      fat: 4.8,
      carbohydrate: 0.0,
      fiber: 0.0,
    ),
    FoodItem(
      name: 'Ikan Kembung',
      category: 'Protein Hewani',
      energyKcal: 103,
      protein: 22.0,
      fat: 1.0,
      carbohydrate: 0.0,
      fiber: 0.0,
    ),
    FoodItem(
      name: 'Ikan Lele',
      category: 'Protein Hewani',
      energyKcal: 95,
      protein: 17.7,
      fat: 2.2,
      carbohydrate: 0.0,
      fiber: 0.0,
    ),
    FoodItem(
      name: 'Ikan Mas',
      category: 'Protein Hewani',
      energyKcal: 86,
      protein: 16.0,
      fat: 2.0,
      carbohydrate: 0.0,
      fiber: 0.0,
    ),
    FoodItem(
      name: 'Ikan Tuna',
      category: 'Protein Hewani',
      energyKcal: 108,
      protein: 22.6,
      fat: 2.0,
      carbohydrate: 0.0,
      fiber: 0.0,
    ),
    FoodItem(
      name: 'Ikan Teri',
      category: 'Protein Hewani',
      energyKcal: 77,
      protein: 16.0,
      fat: 1.0,
      carbohydrate: 0.0,
      fiber: 0.0,
    ),
    FoodItem(
      name: 'Udang',
      category: 'Protein Hewani',
      energyKcal: 91,
      protein: 21.0,
      fat: 0.2,
      carbohydrate: 0.1,
      fiber: 0.0,
    ),
    FoodItem(
      name: 'Cumi-cumi',
      category: 'Protein Hewani',
      energyKcal: 98,
      protein: 17.5,
      fat: 1.8,
      carbohydrate: 3.0,
      fiber: 0.0,
    ),
    
    // ========== PROTEIN NABATI ==========
    FoodItem(
      name: 'Tempe Goreng',
      category: 'Protein Nabati',
      energyKcal: 193,
      protein: 14.0,
      fat: 10.8,
      carbohydrate: 9.9,
      fiber: 1.4,
    ),
    FoodItem(
      name: 'Tempe Mentah',
      category: 'Protein Nabati',
      energyKcal: 149,
      protein: 18.3,
      fat: 4.0,
      carbohydrate: 12.7,
      fiber: 1.4,
    ),
    FoodItem(
      name: 'Tahu Goreng',
      category: 'Protein Nabati',
      energyKcal: 115,
      protein: 10.9,
      fat: 6.9,
      carbohydrate: 2.6,
      fiber: 0.1,
    ),
    FoodItem(
      name: 'Tahu Putih',
      category: 'Protein Nabati',
      energyKcal: 68,
      protein: 7.8,
      fat: 4.2,
      carbohydrate: 1.6,
      fiber: 0.1,
    ),
    FoodItem(
      name: 'Oncom',
      category: 'Protein Nabati',
      energyKcal: 187,
      protein: 13.0,
      fat: 6.0,
      carbohydrate: 22.6,
      fiber: 1.3,
    ),
    FoodItem(
      name: 'Kacang Tanah',
      category: 'Protein Nabati',
      energyKcal: 525,
      protein: 27.9,
      fat: 42.7,
      carbohydrate: 16.7,
      fiber: 2.4,
    ),
    FoodItem(
      name: 'Kacang Hijau Rebus',
      category: 'Protein Nabati',
      energyKcal: 105,
      protein: 7.0,
      fat: 1.2,
      carbohydrate: 19.3,
      fiber: 7.6,
    ),
    FoodItem(
      name: 'Kacang Merah Rebus',
      category: 'Protein Nabati',
      energyKcal: 106,
      protein: 7.5,
      fat: 0.5,
      carbohydrate: 19.7,
      fiber: 6.2,
    ),
    FoodItem(
      name: 'Kedelai Rebus',
      category: 'Protein Nabati',
      energyKcal: 172,
      protein: 16.6,
      fat: 8.1,
      carbohydrate: 10.0,
      fiber: 4.9,
    ),
    
    // ========== SAYURAN ==========
    FoodItem(
      name: 'Bayam',
      category: 'Sayuran',
      energyKcal: 36,
      protein: 3.5,
      fat: 0.5,
      carbohydrate: 6.5,
      fiber: 1.6,
    ),
    FoodItem(
      name: 'Kangkung',
      category: 'Sayuran',
      energyKcal: 29,
      protein: 3.4,
      fat: 0.7,
      carbohydrate: 3.9,
      fiber: 2.0,
    ),
    FoodItem(
      name: 'Sawi Hijau',
      category: 'Sayuran',
      energyKcal: 23,
      protein: 2.3,
      fat: 0.3,
      carbohydrate: 4.0,
      fiber: 1.2,
    ),
    FoodItem(
      name: 'Wortel',
      category: 'Sayuran',
      energyKcal: 42,
      protein: 1.0,
      fat: 0.3,
      carbohydrate: 9.3,
      fiber: 1.0,
    ),
    FoodItem(
      name: 'Kol/Kubis',
      category: 'Sayuran',
      energyKcal: 25,
      protein: 1.4,
      fat: 0.2,
      carbohydrate: 4.6,
      fiber: 1.0,
    ),
    FoodItem(
      name: 'Brokoli',
      category: 'Sayuran',
      energyKcal: 28,
      protein: 3.0,
      fat: 0.4,
      carbohydrate: 5.0,
      fiber: 3.0,
    ),
    FoodItem(
      name: 'Buncis',
      category: 'Sayuran',
      energyKcal: 35,
      protein: 2.4,
      fat: 0.2,
      carbohydrate: 7.7,
      fiber: 1.2,
    ),
    FoodItem(
      name: 'Kacang Panjang',
      category: 'Sayuran',
      energyKcal: 36,
      protein: 2.7,
      fat: 0.4,
      carbohydrate: 7.9,
      fiber: 1.8,
    ),
    FoodItem(
      name: 'Tomat',
      category: 'Sayuran',
      energyKcal: 20,
      protein: 1.0,
      fat: 0.3,
      carbohydrate: 4.2,
      fiber: 0.5,
    ),
    FoodItem(
      name: 'Terong',
      category: 'Sayuran',
      energyKcal: 24,
      protein: 1.1,
      fat: 0.2,
      carbohydrate: 5.5,
      fiber: 2.5,
    ),
    FoodItem(
      name: 'Labu Siam',
      category: 'Sayuran',
      energyKcal: 28,
      protein: 0.8,
      fat: 0.2,
      carbohydrate: 6.7,
      fiber: 0.6,
    ),
    FoodItem(
      name: 'Jagung Manis Rebus',
      category: 'Sayuran',
      energyKcal: 96,
      protein: 3.2,
      fat: 1.3,
      carbohydrate: 21.0,
      fiber: 2.4,
    ),
    FoodItem(
      name: 'Tauge',
      category: 'Sayuran',
      energyKcal: 23,
      protein: 3.2,
      fat: 0.3,
      carbohydrate: 3.3,
      fiber: 1.3,
    ),
    FoodItem(
      name: 'Pare',
      category: 'Sayuran',
      energyKcal: 29,
      protein: 1.1,
      fat: 0.2,
      carbohydrate: 6.6,
      fiber: 1.1,
    ),
    
    // ========== BUAH-BUAHAN ==========
    FoodItem(
      name: 'Pisang Ambon',
      category: 'Buah',
      energyKcal: 99,
      protein: 1.2,
      fat: 0.2,
      carbohydrate: 25.8,
      fiber: 0.6,
    ),
    FoodItem(
      name: 'Pisang Raja',
      category: 'Buah',
      energyKcal: 120,
      protein: 1.2,
      fat: 0.2,
      carbohydrate: 31.8,
      fiber: 0.7,
    ),
    FoodItem(
      name: 'Pisang Kepok',
      category: 'Buah',
      energyKcal: 118,
      protein: 0.8,
      fat: 0.2,
      carbohydrate: 30.0,
      fiber: 0.5,
    ),
    FoodItem(
      name: 'Apel',
      category: 'Buah',
      energyKcal: 58,
      protein: 0.3,
      fat: 0.4,
      carbohydrate: 14.9,
      fiber: 0.7,
    ),
    FoodItem(
      name: 'Jeruk Manis',
      category: 'Buah',
      energyKcal: 45,
      protein: 0.9,
      fat: 0.2,
      carbohydrate: 11.2,
      fiber: 1.0,
    ),
    FoodItem(
      name: 'Pepaya',
      category: 'Buah',
      energyKcal: 46,
      protein: 0.5,
      fat: 0.0,
      carbohydrate: 12.2,
      fiber: 1.6,
    ),
    FoodItem(
      name: 'Mangga',
      category: 'Buah',
      energyKcal: 46,
      protein: 0.6,
      fat: 0.1,
      carbohydrate: 11.6,
      fiber: 0.7,
    ),
    FoodItem(
      name: 'Semangka',
      category: 'Buah',
      energyKcal: 28,
      protein: 0.5,
      fat: 0.2,
      carbohydrate: 6.9,
      fiber: 0.3,
    ),
    FoodItem(
      name: 'Melon',
      category: 'Buah',
      energyKcal: 33,
      protein: 0.6,
      fat: 0.2,
      carbohydrate: 7.9,
      fiber: 0.7,
    ),
    FoodItem(
      name: 'Jambu Biji',
      category: 'Buah',
      energyKcal: 49,
      protein: 0.9,
      fat: 0.3,
      carbohydrate: 12.2,
      fiber: 5.6,
    ),
    FoodItem(
      name: 'Nanas',
      category: 'Buah',
      energyKcal: 52,
      protein: 0.4,
      fat: 0.2,
      carbohydrate: 13.7,
      fiber: 1.0,
    ),
    FoodItem(
      name: 'Anggur',
      category: 'Buah',
      energyKcal: 50,
      protein: 0.7,
      fat: 0.3,
      carbohydrate: 12.6,
      fiber: 0.7,
    ),
    FoodItem(
      name: 'Salak',
      category: 'Buah',
      energyKcal: 77,
      protein: 0.4,
      fat: 0.4,
      carbohydrate: 20.9,
      fiber: 0.3,
    ),
    FoodItem(
      name: 'Rambutan',
      category: 'Buah',
      energyKcal: 69,
      protein: 1.0,
      fat: 0.3,
      carbohydrate: 18.1,
      fiber: 2.0,
    ),
    FoodItem(
      name: 'Durian',
      category: 'Buah',
      energyKcal: 134,
      protein: 2.5,
      fat: 3.0,
      carbohydrate: 27.9,
      fiber: 3.8,
    ),
    FoodItem(
      name: 'Alpukat',
      category: 'Buah',
      energyKcal: 85,
      protein: 0.9,
      fat: 6.5,
      carbohydrate: 7.7,
      fiber: 3.0,
    ),
    
    // ========== MINUMAN ==========
    FoodItem(
      name: 'Susu Sapi Segar',
      category: 'Minuman',
      energyKcal: 61,
      protein: 3.2,
      fat: 3.5,
      carbohydrate: 4.3,
      fiber: 0.0,
    ),
    FoodItem(
      name: 'Susu Kental Manis',
      category: 'Minuman',
      energyKcal: 336,
      protein: 8.0,
      fat: 8.5,
      carbohydrate: 55.5,
      fiber: 0.0,
    ),
    FoodItem(
      name: 'Teh Manis',
      category: 'Minuman',
      energyKcal: 36,
      protein: 0.0,
      fat: 0.0,
      carbohydrate: 9.0,
      fiber: 0.0,
    ),
    FoodItem(
      name: 'Kopi Hitam',
      category: 'Minuman',
      energyKcal: 1,
      protein: 0.1,
      fat: 0.0,
      carbohydrate: 0.0,
      fiber: 0.0,
    ),
    FoodItem(
      name: 'Air Kelapa',
      category: 'Minuman',
      energyKcal: 17,
      protein: 0.2,
      fat: 0.1,
      carbohydrate: 3.8,
      fiber: 0.0,
    ),
    FoodItem(
      name: 'Jus Jeruk',
      category: 'Minuman',
      energyKcal: 51,
      protein: 0.8,
      fat: 0.2,
      carbohydrate: 12.9,
      fiber: 0.2,
    ),
    
    // ========== MAKANAN OLAHAN / GORENGAN ==========
    FoodItem(
      name: 'Bakwan Sayur',
      category: 'Makanan Olahan',
      energyKcal: 165,
      protein: 4.5,
      fat: 8.0,
      carbohydrate: 19.0,
      fiber: 1.5,
    ),
    FoodItem(
      name: 'Tahu Isi',
      category: 'Makanan Olahan',
      energyKcal: 155,
      protein: 6.8,
      fat: 9.5,
      carbohydrate: 11.2,
      fiber: 0.8,
    ),
    FoodItem(
      name: 'Risoles',
      category: 'Makanan Olahan',
      energyKcal: 186,
      protein: 5.5,
      fat: 10.2,
      carbohydrate: 18.3,
      fiber: 1.0,
    ),
    FoodItem(
      name: 'Lemper',
      category: 'Makanan Olahan',
      energyKcal: 168,
      protein: 5.0,
      fat: 4.5,
      carbohydrate: 28.5,
      fiber: 0.8,
    ),
    FoodItem(
      name: 'Kroket',
      category: 'Makanan Olahan',
      energyKcal: 188,
      protein: 6.2,
      fat: 11.5,
      carbohydrate: 15.8,
      fiber: 1.2,
    ),
    FoodItem(
      name: 'Perkedel Kentang',
      category: 'Makanan Olahan',
      energyKcal: 158,
      protein: 4.8,
      fat: 8.5,
      carbohydrate: 16.5,
      fiber: 1.5,
    ),
    FoodItem(
      name: 'Siomay',
      category: 'Makanan Olahan',
      energyKcal: 112,
      protein: 7.5,
      fat: 4.2,
      carbohydrate: 11.8,
      fiber: 0.5,
    ),
    FoodItem(
      name: 'Batagor',
      category: 'Makanan Olahan',
      energyKcal: 165,
      protein: 8.2,
      fat: 9.5,
      carbohydrate: 12.5,
      fiber: 0.8,
    ),
  ];

  // Fungsi search makanan
  static List<FoodItem> searchFoods(String query) {
    if (query.isEmpty) return foods;
    
    return foods.where((food) {
      return food.name.toLowerCase().contains(query.toLowerCase()) ||
             food.category.toLowerCase().contains(query.toLowerCase());
    }).toList();
  }

  // Get makanan berdasarkan kategori
  static List<FoodItem> getFoodsByCategory(String category) {
    return foods.where((food) => food.category == category).toList();
  }

  // Get semua kategori
  static List<String> getCategories() {
    return foods.map((food) => food.category).toSet().toList();
  }
}